package ir.sharif.gamein2021.core.util;

public class DatabaseConstants {
    public static final String DATABASE_LOCATION = "redis://localhost:6379/";
    public static final int ID_DATABASE = 0;
    public static final int LAND_DATABASE = 1;
    public static final int MACHINE_DATABASE = 2;
    public static final int PLAYER_DATABASE = 4;
    public static final int TIME_DATABASE = 6;
    public static final int MACHINE_TYPE_DATABASE = 8;
    public static final int RFQ_DATABASE = 9;
    public static final int PLAYER_SENT_RFQ_DATABASE = 10;
    public static final int PLAYER_RECEIVED_RFQ_DATABASE = 11;
    public static final int RFQ_OFFER_DATABASE = 12;
    public static final int PLAYER_SENT_RFQ_OFFER_DATABASE = 13;
    public static final int PLAYER_RECEIVED_RFQ_OFFER_DATABASE = 14;
    public static final int RFQ_TO_OFFER_DATABASE = 15;
    public static final int RFQ_CONTRACTS_DATABASE = 16;
    public static final int BUYER_RFQ_CONTRACT_DATABASE = 17;
    public static final int SELLER_RFQ_CONTRACT_DATABASE = 18;
    public static final int CONTRACT_TIME_DATABASE = 19;
    public static final int DELIVERY_DATABASE = 21;
    public static final int PLAYER_PAST_FUNDRAISES = 22;
    public static final int RANKINGS_DATABASE = 23;
    public static final int PLAYER_TO_RANKINGS_DATABASE = 24;
    public static final int FINAL_PRODUCT_OFFER_DATABASE = 25;
    public static final int COUNTRY_FINAL_PRODUCT_DATABASE = 26;
    public static final int TIME_TO_FUNDRAISE_DATABASE = 27;
    public static final int FUNDRAISE_TO_OFFER_DATABASE = 28;
    public static final int MACHINE_BUILD_DATABASE = 29;
    public static final int PLAYER_PAST_INVESTS = 30;
    public static final int TIME_TO_RFQ_DATABASE = 31;
    public static final int PLAYER_TO_INVESTOR_DATABASE = 32;
    public static final int FUNDRAISE_DATABASE = 33;
    public static final int PLAYER_TO_INVESTEE_DATABASE = 34;
    public static final int FUNDRAISING_DEADLINE = 35;
    public static final int INTERMEDIATE_PRODUCT_OFFER_DATABASE = 36;
    public static final int COUNTRY_INTERMEDIATE_PRODUCT_OFFER_DATABASE = 37;
    public static final int TIME_TO_GAMEIN_BUY_DATABASE = 38;
    public static final int PLAYER_TO_SCORE_LIST_DATABASE = 39;
    public static final int LOAN_DATABASE = 40;
    public static final int USER_PASS_DATABASE = 41;
    public static final int USER_PLAYER_DATABASE = 42;
    public static final int BONUS_DATABASE = 43;
    public static final int SHOCK_DATABASE = 44;
    public static final int LAND_TO_INCOMING_PRODUCT_DATABASE = 45;
    public static final int DELTA_TIME_DATABASE = 47;
}
