package ir.sharif.gamein2021.core.util;

public enum RequestTypeConstant
{
    LOGIN(0),
    NEW_OFFER(1),
    GET_OFFERS(2),
    GET_GAME_DATA(3),
    GET_CONTRACTS(4),
    ACCEPT_OFFER(5),
    GET_NEGOTIATIONS(6),
    EDIT_NEGOTIATION_COST_PER_UNIT(7),
    NEW_PROVIDER(8),
    GET_PROVIDERS(9),
    REMOVE_PROVIDER(10),
    NEW_PROVIDER_NEGOTIATION(11),
    BID_FOR_AUCTION(12),
    TERMINATE_OFFER(13),
    NEW_MESSAGE(14),
    GET_ALL_CHATS(15),
    GET_PRODUCTION_LINES(16),
    CONSTRUCT_PRODUCTION_LINE(17),
    SCRAP_PRODUCTION_LINE(18),
    START_PRODUCTION(19),
    UPGRADE_PRODUCTION_LINE_QUALITY(20),
    UPGRADE_PRODUCTION_LINE_EFFICIENCY(21),
    NEW_CONTRACT_WITH_SUPPLIER(22),
    TERMINATE_LONGTERM_CONTRACT_WITH_SUPPLIER(23),
    BUY_DC(24),
    SELL_DC(25),
    GET_TEAM_TRANSPORTS(26),
    GET_CONTRACTS_WITH_SUPPLIER(27),
    ADD_PRODUCT(28),
    REMOVE_PRODUCT(29),
    GET_STORAGES(30),
    NEW_CONTRACT(31),
    TERMINATE_CONTRACT(32),
    GET_GAME_STATUS(33),
    TRANSPORT_TO_STORAGE(34),
    GET_ALL_WEEKLY_REPORTS(35),
    REJECT_NEGOTIATION(36),
    EDIT_PROVIDER(37),
    DONATE(38);

    private int value;

    RequestTypeConstant(int value)
    {
        this.value = value;
    }
}
